export const GET_ITEM_DETAILS = 'GET_ITEM_DETAILS';
export const GET_ITEM_DETAILS_OK = 'GET_ITEM_DETAILS_OK';

export const CLEAR_ITEM_DETAILS = 'CLEAR_ITEM_DETAILS';
export const CLEAR_ITEM_DETAILS_OK = 'CLEAR_ITEM_DETAILS_OK';
