export const GET_TOP_STORIES = 'GET_TOP_STORIES';
export const GET_TOP_STORIES_OK = 'GET_TOP_STORIES_OK';

export const GET_TOP_STORIES_INFO = 'GET_TOP_STORIES_INFO';
export const GET_TOP_STORIES_INFO_OK = 'GET_TOP_STORIES_INFO_OK';

export const SET_TOP_STORY_REFRESHING = 'SET_TOP_STORY_REFRESHING';
export const SET_TOP_STORY_REFRESHING_OK = 'SET_TOP_STORY_REFRESHING_OK';
